appsrap:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  base-url-client:
    github: "https://api.github.com"
    stackoverflow: "https://api.stackexchange.com/2.3"
    bot: "http://localhost:8090/v0/bot"
  database-access-type: jpa

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
