/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.enums;


import edu.java.scrapper.domain.jooq.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum ResourceType implements EnumType {

    GITHUB("GITHUB"),

    STACKOVERFLOW("STACKOVERFLOW");

    private final String literal;

    private ResourceType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "RESOURCE_TYPE";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ResourceType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ResourceType.class, literal);
    }
}
