app:
  telegram-token: 6600925304:AAGGB9R9zVjPlqCE1OvxgFuht0z2CNa7ooQ


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
