/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.ChatLinks;
import edu.java.scrapper.domain.jooq.tables.Chats;
import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.records.ChatLinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.ChatsRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinksRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatLinksRecord> CONSTRAINT_49 = Internal.createUniqueKey(ChatLinks.CHAT_LINKS, DSL.name("CONSTRAINT_49"), new TableField[] { ChatLinks.CHAT_LINKS.CHAT_ID, ChatLinks.CHAT_LINKS.LINK_ID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3D = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3D"), new TableField[] { Chats.CHATS.CHAT_ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinksRecord, ChatsRecord> CONSTRAINT_49D = Internal.createForeignKey(ChatLinks.CHAT_LINKS, DSL.name("CONSTRAINT_49D"), new TableField[] { ChatLinks.CHAT_LINKS.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { Chats.CHATS.ID }, true);
    public static final ForeignKey<ChatLinksRecord, LinksRecord> CONSTRAINT_49D6 = Internal.createForeignKey(ChatLinks.CHAT_LINKS, DSL.name("CONSTRAINT_49D6"), new TableField[] { ChatLinks.CHAT_LINKS.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
}
